server:
  port: 9999
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/team_project?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456


  mvc:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations: file:D://images/
  devtools:
    restart:
      enabled: true
mybatis-plus:
  type-aliases-package: com.lauheng.model
  configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/lauheng/dao/*.xml
